spring:
  #
  # thymeleaf 配置
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.6:3306/seckill?useUnicode=true&characterEncodings=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认 10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认 1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认 30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true
        html-application-cache: cli
      static-locations: classpath:/static/
  # redis configuration
  redis:
    host: 192.168.10.6
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: miaosharedis
  # rabbitMQ
  rabbitmq:
    host: 192.168.10.6
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 1000ms
        multiplier: 1

# Mybatis-Plus 配置
mybatis-plus:
  # Mapper.xml 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #  配置 MyBatis 数据返回类型别名（默认别名是类名）
  type-aliases-package: com.eterlar.seckillsystem.pojo

# Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.eterlar.seckillsystem: debug